version: '3.8'

services:
  # 1. Сервис самой базы данных MongoDB
  mongodb:
    image: mongo:latest
    container_name: hatahelper_mongodb
    restart: always
    ports:
      - "27017:27017" # Пробрасываем порт: левый - мак, правый - докер
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: secretpassword
    volumes:
      - mongo_data:/data/db # Сохраняем данные базы в виртуальный том Docker

  # 2. Веб-интерфейс для удобного просмотра данных (Mongo Express)
  mongo-express:
      image: mongo-express:latest
      container_name: hatahelper_mongo_express
      restart: always
      ports:
        - "8081:8081"
      environment:
        ME_CONFIG_MONGODB_ADMINUSERNAME: admin
        ME_CONFIG_MONGODB_ADMINPASSWORD: secretpassword
        ME_CONFIG_MONGODB_SERVER: mongodb
        # Отключаем всплывающее окно с авторизацией для локалки:
        ME_CONFIG_BASICAUTH: "false"
      depends_on:
        - mongodb

# Объявляем том для сохранения данных (чтобы данные не удалялись при выключении)
volumes:
  mongo_data: